name: CI

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go get -v -t ./...

    - name: Test with coverage
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.txt
        fail_ci_if_error: true

    - name: Build Docker image
      run: docker build -t netexecgo:latest .

    - name: Push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: netexecgo:latest
