name: Build and Release

on:
  push:
    tags:
    - 'v*'
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        go-version: ['1.21']
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=amd64 go build -o netexecgo-${{ matrix.os }}-${{ matrix.go-version }} main.go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: netexecgo-${{ matrix.os }}-${{ matrix.go-version }}
        path: netexecgo-${{ matrix.os }}-${{ matrix.go-version }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          netexecgo-linux-${{ matrix.go-version }}
          netexecgo-darwin-${{ matrix.go-version }}
          netexecgo-windows-${{ matrix.go-version }}
